### ISSUE TITLE
Add interactive shell variants

### ISSUE THREAD

**Issue by yaahc** [Proksima/shells#1]
I wanted to be able to run a bash shell script interactively as a WIP of converting some bash script cli tools to rust incrementally. As far as I can tell this isn't possible with the macro's you exported. I think it would be a good idea to add a variant like this.

```rust
pub fn execute_interactive_with(shell: &str, cmd: &String) -> i32 {
    let mut command = {
        let mut command = ::std::process::Command::new(shell);
        command.arg("-c").arg(cmd);
        command
    };

    match command.spawn() {
        Ok(mut child) => {
            let status = child.wait().expect("command wasn't running");
            status
                .code()
                .unwrap_or(if status.success() { 0 } else { 1 })
        }
        Err(_) => 126,
    }
}

macro_rules! ibash {
    ( $( $cmd:tt )* ) => {{
        $crate::execute_interactive_with("bash", &format!($( $cmd )*))
    }};
}
```

not sure how I feel about discarding the error return code from spawn and turning it straight into a 126, you can adjust as you feel necessary. If you want help I don't mind setting up a PR. The only reason I haven't already set up a PR is in case you're not interested in which case I'll just keep using the version above.

**Comment by Proksima** [comment]
I am not sure this does what you think it does:

"[Child::wait()] waits for the child to exit completely, returning the status that it exited with. This function will continue to have the same return value after it has been called at least once.

[Most importantly] The stdin handle to the child process, if any, will be closed before waiting."

Did you test it and make sure it exhibit the behavior you want?

**Comment by yaahc** [comment]
It does seem to work as expected with the version shown above. I do think that the better solution would be to use command.status() rather than command.spawn(). I think I was vaguely trying to look into getting a copy of the stdin and stdout/stderr from the command but digging into it made that seem impossible, also I had no real need for those, I just was wondering if you could get an interactive shell that still returns the same values that the non interactive one does.

```rust
fn execute_interactive_with(shell: &str, cmd: &str) -> i32 {
    let mut command = {
        let mut command = ::std::process::Command::new(shell);
        command.arg("-c").arg(cmd);
        command
    };

    match command.status() {
        Ok(status) => status
            .code()
            .unwrap_or(if status.success() { 0 } else { 1 }),
        Err(_) => 126,
    }
}
```

**Comment by Proksima** [comment]
Maybe I am the one who do not understand, for me an interactive shell is:

"An interactive shell reads commands from user input on a tty. Among other things, such a shell reads startup files on activation, displays a prompt, and enables job control by default. The user can interact with the shell. A shell running a script is always a non-interactive shell."

I do not understand why running the command as a child process makes it interactive. I also do not see how you will interact with the command after it is spawned or whether just adding a '-i' argument (which makes POSIX shell interactives) would do what you want...

I mean, I have nothing against adding a feature; I'm actually happy to see this is useful to some people. How about you send me a rust file with an integrated test that show me the implementation and the intended behaviour and if all is well, I will add the feature to the crate.

**Comment by yaahc** [comment]
I think I'm using the incorrect terms. What I needed was to have the subprocess inherit stdin/stdout and stderr from the rust program, so that I can run something like `ibash{"rev"}` and it will let me type input and hit enter and it will immediately print it back to the screen reversed. Or I could run `ibash{"bash -i"}` to get an actual interactive shell I think based on your description.

I'm essentially trying to make the following behave identically.

```bash
#!/bin/bash

rev
echo $?
```

```rust
fn main() {
    let status = ibash!("rev");
    println!("{}", status);
}
```

I don't know how to properly integration test this, but figure it out and submit a pr.
